includes:
  - configs/datasets/hateful_memes/bert.yaml

env:
  save_dir: ./runs/tatp-d08

dataset_config:
  hateful_memes:
    annotations:
      train:
        - hateful_memes/defaults/annotations/train_tatp.jsonl

model_config:
  concat_bert:
    classifier:
      type: mlp
      params:
        num_layers: 2
        dropout: 0.8
    losses:
      - type: cross_entropy

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 2000
    num_training_steps: ${training.max_updates}

optimizer:
  type: adam_w
  params:
    lr: 1e-5
    eps: 1e-8

evaluation:
  metrics:
    - accuracy
    - binary_f1
    - roc_auc

training:
  seed: 15192421
  batch_size: 64
  lr_scheduler: true
  max_updates: 22000
  early_stop:
    criteria: hateful_memes/roc_auc
    minimize: false

checkpoint:
  pretrained_state_mapping:
    base: base
